let autos = [
    {
        marca: "Ford",
        modelo: "Fiesta",
        precio: 150000,
        km: 200,
        color: "Azul",
        cuotas: 12,
        anio: 2019,
        patente: "APL123",
        vendido: false,
    },
    {
        marca: "Toyota",
        modelo: "Corolla",
        precio: 100000,
        km: 0,
        color: "Blanco",
        cuotas: 14,
        anio: 2019,
        patente: "JJK116",
        vendido: false,
    },
    {
        marca: "Toyota",
        modelo: "Etios",
        precio: 120000,
        km: 0,
        color: "Gris",
        cuotas: 13,
        anio: 2019,
        patente: "JJK666",
        vendido: false,
    },
    {
        marca: "Nissan",
        modelo: "Versa",
        precio: 100000,
        km: 0,
        color: "Gris",
        cuotas: 11,
        anio: 2021,
        patente: "HJH216",
        vendido: false,
    },
    {
        marca: "Nissan",
        modelo: "Sentra",
        precio: 130000,
        km: 0,
        color: "Naranja",
        cuotas: 14,
        anio: 2020,
        patente: "JJG119",
        vendido: false,
    },
];

module.exports = autos;
